/* MYMENU.rexx - Main category menu. Visibility via QUERY SECURITY. */
EXEC CICS ASSIGN USERID(UID) DATE(TODAY) TIME(NOWTIME) END-EXEC
DISPDATE = SUBSTR(TODAY,5,2)'/'SUBSTR(TODAY,7,2)'/'SUBSTR(TODAY,1,4)
DISPTIME = SUBSTR(NOWTIME,1,2)':'SUBSTR(NOWTIME,3,2)':'SUBSTR(NOWTIME,5,2)

ROLESTR = 'ACCESS: PUBLIC'
IF STRIP(UID) \= '' THEN DO
  EXEC CICS QUERY SECURITY RESOURCE('SQLM') READ(RSQL) END-EXEC
  IF EIBRESP = 0 & RSQL = 50 THEN ROLESTR = 'ACCESS: ADMIN'
  ELSE ROLESTR = 'ACCESS: USER'
END

OUT.DATFLD = DISPDATE
OUT.TIMFLD = DISPTIME
OUT.USRFLD = STRIP(UID)
OUT.ROLEFLD = ROLESTR

N = 0
N = N+1; CATID.N = 'REXM'; CATDESC.N = 'REXX PROGRAMS'
N = N+1; CATID.N = 'COBM'; CATDESC.N = 'COBOL PROGRAMS'
N = N+1; CATID.N = 'CUSM'; CATDESC.N = 'CUSTOMER / CONTACTS'
N = N+1; CATID.N = 'QUEM'; CATDESC.N = 'QUEUE AND STORAGE'
N = N+1; CATID.N = 'SQLM'; CATDESC.N = 'SQL / DATABASE'
N = N+1; CATID.N = 'SYSM'; CATDESC.N = 'SYSTEM AND ADMIN'
TOTALCAT = N

VISCOUNT = 0
DO I = 1 TO TOTALCAT
  OK = 51
  RID = CATID.I
  EXEC CICS QUERY SECURITY RESOURCE(RID) READ(OK) END-EXEC
  IF EIBRESP = 0 & OK = 50 THEN DO
    VISCOUNT = VISCOUNT + 1
    VISID.VISCOUNT = CATID.I
    VISDESC.VISCOUNT = CATDESC.I
  END
END
VISCOUNT = VISCOUNT + 1
VISID.VISCOUNT = 'LOFF'
VISDESC.VISCOUNT = 'EXIT TO PROMPT'

PAGESIZE = 8
DO SLOT = 1 TO PAGESIZE
  NUM = RIGHT(SLOT,2,'0')
  INTERPRET "OUT.L"||NUM" = ''"
END
DO V = 1 TO VISCOUNT
  NUM = RIGHT(V,2,'0')
  INTERPRET "OUT.L"||NUM" = LEFT(NUM'.  'VISDESC.V, 38)"
END
OUT.FOOTFLD = 'PF1=EXIT   PF9=HELP   ENTER=SELECT'

EXEC CICS SEND MAP('MYMENU') MAPSET('MYMENU') FROM(OUT.) ERASE END-EXEC
EXEC CICS RECEIVE MAP('MYMENU') MAPSET('MYMENU') INTO(IN.) END-EXEC

AID = C2X(EIBAID)
IF AID = 'F1' THEN EXEC CICS RETURN END-EXEC
IF AID = 'F9' THEN DO
  CA = 'MYMU'
  EXEC CICS XCTL PROGRAM('MHLP') COMMAREA(CA) END-EXEC
END

SEL = STRIP(IN.SELFLD)
IF DATATYPE(SEL,'N') THEN DO
  SELNUM = SEL + 0
  IF SELNUM >= 1 & SELNUM <= VISCOUNT THEN DO
    IF VISID.SELNUM = 'LOFF' THEN EXEC CICS RETURN END-EXEC
    DEST = VISID.SELNUM
    EXEC CICS XCTL PROGRAM(DEST) END-EXEC
  END
END
EXEC CICS RETURN TRANSID('MYMU') END-EXEC
