/* QUEMENU.rexx - Queue, files, and storage submenu. QUERY SECURITY. */
EXEC CICS ASSIGN USERID(UID) DATE(TODAY) TIME(NOWTIME) END-EXEC
DISPDATE = SUBSTR(TODAY,5,2)'/'SUBSTR(TODAY,7,2)'/'SUBSTR(TODAY,1,4)
DISPTIME = SUBSTR(NOWTIME,1,2)':'SUBSTR(NOWTIME,3,2)':'SUBSTR(NOWTIME,5,2)

ROLESTR = 'ACCESS: PUBLIC'
IF STRIP(UID) \= '' THEN DO
  EXEC CICS QUERY SECURITY RESOURCE('SQLM') READ(RSQL) END-EXEC
  IF EIBRESP = 0 & RSQL = 50 THEN ROLESTR = 'ACCESS: ADMIN'
  ELSE ROLESTR = 'ACCESS: USER'
END
OUT.DATFLD = DISPDATE; OUT.TIMFLD = DISPTIME
OUT.USRFLD = STRIP(UID); OUT.ROLEFLD = ROLESTR

N = 0
N = N+1; TXID.N = 'QAGE'; TXDESC.N = 'QUEUE AGE (REXX)'
N = N+1; TXID.N = 'QAGR'; TXDESC.N = 'QUEUE AGE RESULT'
N = N+1; TXID.N = 'QAGC'; TXDESC.N = 'QUEUE AGE (COBOL)'
N = N+1; TXID.N = 'QUEN'; TXDESC.N = 'QUEUE ENQUEUE'
N = N+1; TXID.N = 'PROD'; TXDESC.N = 'TS PRODUCER'
N = N+1; TXID.N = 'CONS'; TXDESC.N = 'TS CONSUMER'
N = N+1; TXID.N = 'GETC'; TXDESC.N = 'GET RECORD'
N = N+1; TXID.N = 'ESDC'; TXDESC.N = 'ESDS (COBOL)'
N = N+1; TXID.N = 'ESDR'; TXDESC.N = 'ESDS (REXX)'
N = N+1; TXID.N = 'ORDR'; TXDESC.N = 'ORDER IMPORT'
TOTALMASTER = N

VISCOUNT = 0
DO I = 1 TO TOTALMASTER
  OK = 51
  RID = TXID.I
  EXEC CICS QUERY SECURITY RESOURCE(RID) READ(OK) END-EXEC
  IF EIBRESP = 0 & OK = 50 THEN DO
    VISCOUNT = VISCOUNT + 1
    VISID.VISCOUNT = TXID.I
    VISDESC.VISCOUNT = TXDESC.I
  END
END

PAGESIZE = 14
DO SLOT = 1 TO PAGESIZE
  NUM = RIGHT(SLOT,2,'0')
  INTERPRET "OUT.L"||NUM" = ''"
END
SLOT = 0
IF VISCOUNT = 0 THEN DO
  OUT.L01 = '(NO AUTHORIZED ITEMS)'
END
ELSE DO V = 1 TO VISCOUNT
  SLOT = SLOT + 1
  NUM = RIGHT(V,2,'0')
  INTERPRET "OUT.L"||NUM" = LEFT(NUM'.  'VISID.V'  'VISDESC.V, 38)"
END
OUT.FOOTFLD = 'PF3=MAIN  PF9=HELP   ENTER=SELECT'

EXEC CICS SEND MAP('QUEMENU') MAPSET('QUEMENU') FROM(OUT.) ERASE END-EXEC
EXEC CICS RECEIVE MAP('QUEMENU') MAPSET('QUEMENU') INTO(IN.) END-EXEC

AID = C2X(EIBAID)
IF AID = 'F1' | AID = 'F3' THEN EXEC CICS RETURN TRANSID('MYMU') END-EXEC
IF AID = 'F9' THEN DO
  CA = 'QUEM'
  EXEC CICS XCTL PROGRAM('MHLP') COMMAREA(CA) END-EXEC
END

SEL = STRIP(IN.SELFLD)
IF DATATYPE(SEL,'N') THEN DO
  SELNUM = SEL + 0
  IF SELNUM >= 1 & SELNUM <= SLOT THEN DO
    DEST = VISID.SELNUM
    EXEC CICS XCTL PROGRAM(DEST) END-EXEC
  END
END
EXEC CICS RETURN TRANSID('QUEM') END-EXEC
