# transactions.conf -- managed by CEDA TRANSACTION and operator vi.
# Format: TRANSID:LANG:PROGRAM[:GROUP1,GROUP2,...[:DATABASE[:TWASIZE]]]
# TWASIZE (6th, positional) = per-task TWA bytes 0..32767 for ADDRESS TWA.
BALC:cobol:balc.cob:PUBLIC:bank
BALR:rexx:balc.rexx:PUBLIC:bank
BANK:cobol:bank.cob:PUBLIC,USERS,ADMIN:bank
BOOK:rexx:book.rexx:PUBLIC
BRDS:rexx:brds.rexx:USERS:bank
CHAT:rexx:chat.rexx:PUBLIC,USERS,ADMIN
CHEL:cobol:help.cob:PUBLIC
CONS:rexx:cons.rexx:USERS,ADMIN
CSGM:rexx:csgm.rexx:PUBLIC,USERS,ADMIN
CSSR:rexx:cssr.rexx:USERS,ADMIN
CUSL:rexx:cusl.rexx:PUBLIC
CUST:rexx:cust.rexx:PUBLIC
CUSV:rexx:cusv.rexx:PUBLIC
ESDC:cobol:esdc.cob:PUBLIC,USERS,ADMIN
ESDR:rexx:esdr.rexx:PUBLIC,USERS,ADMIN
ESPF:rexx:espf.rexx:ADMIN
EXAM:cobol:exam.cob:PUBLIC
EXAR:rexx:exam.rexx:PUBLIC
FSPF:rexx:fspf.rexx:PUBLIC
FUNC:rexx:func.rexx:PUBLIC
GETC:rexx:getc.rexx:PUBLIC,USERS,ADMIN
GMPT:cobol:gmpt.cob:PUBLIC
GUSL:cobol:gusl.cob:PUBLIC
GUST:cobol:gust.cob:PUBLIC
GUSV:cobol:gusv.cob:PUBLIC
INQR:rexx:inqr.rexx:PUBLIC
HELC:cobol:hello.cob:PUBLIC
HELO:rexx:hello.rexx:PUBLIC
HELP:rexx:help.rexx:PUBLIC,USERS,ADMIN
MNDL:rexx:mndl.rexx:PUBLIC,USERS,ADMIN
MNDU:rexx:mndu.rexx:PUBLIC,USERS,ADMIN
ORDR:cobol:ordr.cob:PUBLIC
PROD:rexx:prod.rexx:USERS,ADMIN
QAGC:cobol:qagc.cob:PUBLIC,USERS,ADMIN
QAGE:rexx:qage.rexx:PUBLIC,USERS,ADMIN
QAGR:rexx:qagr.rexx:PUBLIC,USERS,ADMIN
QUEN:rexx:quen.rexx:PUBLIC
SABR:rexx:book.rexx:PUBLIC
STAR:cobol:star.cob:PUBLIC:blank
SQLD:cobol:sqld.cob:PUBLIC,USERS,ADMIN
SQLR:rexx:sqlr.rexx:PUBLIC,USERS,ADMIN
TIMC:cobol:timc.cob:PUBLIC,USERS,ADMIN
TIME:rexx:time.rexx:PUBLIC
TIMR:rexx:timr.rexx:PUBLIC,USERS,ADMIN
TOPX:cobol:topx.cob:PUBLIC:test3270
UPPR:cobol:uppr.cob:PUBLIC
WAPI:rexx:wapi.rexx:PUBLIC,USERS,ADMIN
WHDR:cobol:whdr.cob:PUBLIC,USERS,ADMIN
WZEN:cobol:wzen.cob:PUBLIC,USERS,ADMIN

# --- keoni-custom additions (DODFMR + PERS sample extensions) ---
DODC:cobol:dodfr.cob:PUBLIC,USERS,ADMIN
PERL:cobol:persl.cob:PUBLIC,USERS,ADMIN
PERV:cobol:persv.cob:PUBLIC,USERS,ADMIN
PERS:cobol:pers.cob:PUBLIC,USERS,ADMIN
DODF:rexx:dodfr.rexx:PUBLIC,USERS,ADMIN
