/* COBMENU.rexx - COBOL programs submenu. QUERY SECURITY + PF7/PF8 paging. */
EXEC CICS ASSIGN USERID(UID) DATE(TODAY) TIME(NOWTIME) EIBCALEN(CALEN) END-EXEC
DISPDATE = SUBSTR(TODAY,5,2)'/'SUBSTR(TODAY,7,2)'/'SUBSTR(TODAY,1,4)
DISPTIME = SUBSTR(NOWTIME,1,2)':'SUBSTR(NOWTIME,3,2)':'SUBSTR(NOWTIME,5,2)

ROLESTR = 'ACCESS: PUBLIC'
IF STRIP(UID) \= '' THEN DO
  EXEC CICS QUERY SECURITY RESOURCE('SQLM') READ(RSQL) END-EXEC
  IF EIBRESP = 0 & RSQL = 50 THEN ROLESTR = 'ACCESS: ADMIN'
  ELSE ROLESTR = 'ACCESS: USER'
END
OUT.DATFLD = DISPDATE; OUT.TIMFLD = DISPTIME
OUT.USRFLD = STRIP(UID); OUT.ROLEFLD = ROLESTR

N = 0
N = N+1; TXID.N = 'HELC'; TXDESC.N = 'HELLO'
N = N+1; TXID.N = 'CHEL'; TXDESC.N = 'HELP COBOL'
N = N+1; TXID.N = 'EXAM'; TXDESC.N = 'EXAM ARGS'
N = N+1; TXID.N = 'BALC'; TXDESC.N = 'COLOR / UNDERLINE'
N = N+1; TXID.N = 'BANK'; TXDESC.N = 'BANK DEMO'
N = N+1; TXID.N = 'ORDR'; TXDESC.N = 'ORDER IMPORT'
N = N+1; TXID.N = 'TIMC'; TXDESC.N = 'TIMER'
N = N+1; TXID.N = 'QAGC'; TXDESC.N = 'QUEUE AGE'
N = N+1; TXID.N = 'SQLD'; TXDESC.N = 'SQL DEMO'
N = N+1; TXID.N = 'ESDC'; TXDESC.N = 'ESDS SEQUENTIAL'
N = N+1; TXID.N = 'GUST'; TXDESC.N = 'CUSTOMER MAINT'
N = N+1; TXID.N = 'PERS'; TXDESC.N = 'CONTACTS'
N = N+1; TXID.N = 'DODC'; TXDESC.N = 'DODFMR (COBOL)'
N = N+1; TXID.N = 'WHDR'; TXDESC.N = 'WEB HEADERS'
N = N+1; TXID.N = 'WZEN'; TXDESC.N = 'WEB ZEN'
N = N+1; TXID.N = 'UPPR'; TXDESC.N = 'INSPECT CONVERTING'
N = N+1; TXID.N = 'GMPT'; TXDESC.N = 'GETMAIN / POINTERS'
N = N+1; TXID.N = 'TOPX'; TXDESC.N = '3270BBS'
N = N+1; TXID.N = 'STAR'; TXDESC.N = 'STAR WARS'
TOTALMASTER = N

VISCOUNT = 0
DO I = 1 TO TOTALMASTER
  OK = 51
  RID = TXID.I
  EXEC CICS QUERY SECURITY RESOURCE(RID) READ(OK) END-EXEC
  IF EIBRESP = 0 & OK = 50 THEN DO
    VISCOUNT = VISCOUNT + 1
    VISID.VISCOUNT = TXID.I
    VISDESC.VISCOUNT = TXDESC.I
  END
END

PAGESIZE = 14
PAGE = 1
IF CALEN >= 1 THEN DO
  PAGE = STRIP(DFHCOMMAREA) + 0
  IF PAGE < 1 THEN PAGE = 1
END
NPAGES = 1
IF VISCOUNT > 0 THEN NPAGES = (VISCOUNT + PAGESIZE - 1) % PAGESIZE
IF PAGE > NPAGES THEN PAGE = NPAGES
FIRST = (PAGE - 1) * PAGESIZE + 1
LAST = FIRST + PAGESIZE - 1
IF LAST > VISCOUNT THEN LAST = VISCOUNT

DO SLOT = 1 TO PAGESIZE
  NUM = RIGHT(SLOT,2,'0')
  INTERPRET "OUT.L"||NUM" = ''"
END
SLOT = 0
IF VISCOUNT = 0 THEN DO
  OUT.L01 = '(NO AUTHORIZED ITEMS)'
END
ELSE DO V = FIRST TO LAST
  SLOT = SLOT + 1
  NUM = RIGHT(SLOT,2,'0')
  INTERPRET "OUT.L"||NUM" = LEFT(NUM'.  'VISID.V'  'VISDESC.V, 38)"
END
OUT.FOOTFLD = LEFT('PF3=MAIN  PF9=HELP  PF7=BWD  PF8=FWD   PAGE '||PAGE||'/'||NPAGES, 78)

EXEC CICS SEND MAP('COBMENU') MAPSET('COBMENU') FROM(OUT.) ERASE END-EXEC
EXEC CICS RECEIVE MAP('COBMENU') MAPSET('COBMENU') INTO(IN.) END-EXEC

AID = C2X(EIBAID)
IF AID = 'F1' | AID = 'F3' THEN EXEC CICS RETURN TRANSID('MYMU') END-EXEC
IF AID = 'F9' THEN DO
  CA = 'COBM'
  EXEC CICS XCTL PROGRAM('MHLP') COMMAREA(CA) END-EXEC
END
IF AID = 'F7' THEN DO
  PAGE = PAGE - 1
  IF PAGE < 1 THEN PAGE = 1
  EXEC CICS RETURN TRANSID('COBM') COMMAREA(PAGE) END-EXEC
END
IF AID = 'F8' THEN DO
  PAGE = PAGE + 1
  IF PAGE > NPAGES THEN PAGE = NPAGES
  EXEC CICS RETURN TRANSID('COBM') COMMAREA(PAGE) END-EXEC
END

SEL = STRIP(IN.SELFLD)
IF DATATYPE(SEL,'N') THEN DO
  SELNUM = SEL + 0
  IDX = FIRST + SELNUM - 1
  IF SELNUM >= 1 & SELNUM <= SLOT THEN DO
    DEST = VISID.IDX
    EXEC CICS XCTL PROGRAM(DEST) END-EXEC
  END
END
EXEC CICS RETURN TRANSID('COBM') COMMAREA(PAGE) END-EXEC
