/* REXMENU.rexx - REXX programs submenu. QUERY SECURITY + PF7/PF8 paging. */
EXEC CICS ASSIGN USERID(UID) DATE(TODAY) TIME(NOWTIME) EIBCALEN(CALEN) END-EXEC
DISPDATE = SUBSTR(TODAY,5,2)'/'SUBSTR(TODAY,7,2)'/'SUBSTR(TODAY,1,4)
DISPTIME = SUBSTR(NOWTIME,1,2)':'SUBSTR(NOWTIME,3,2)':'SUBSTR(NOWTIME,5,2)

ROLESTR = 'ACCESS: PUBLIC'
IF STRIP(UID) \= '' THEN DO
  EXEC CICS QUERY SECURITY RESOURCE('SQLM') READ(RSQL) END-EXEC
  IF EIBRESP = 0 & RSQL = 50 THEN ROLESTR = 'ACCESS: ADMIN'
  ELSE ROLESTR = 'ACCESS: USER'
END
OUT.DATFLD = DISPDATE; OUT.TIMFLD = DISPTIME
OUT.USRFLD = STRIP(UID); OUT.ROLEFLD = ROLESTR

N = 0
N = N+1; TXID.N = 'HELO'; TXDESC.N = 'HELLO'
N = N+1; TXID.N = 'HELP'; TXDESC.N = 'SAMPLE HELP'
N = N+1; TXID.N = 'EXAR'; TXDESC.N = 'EXAM ARGS'
N = N+1; TXID.N = 'TIME'; TXDESC.N = 'TIME'
N = N+1; TXID.N = 'TIMR'; TXDESC.N = 'TIMER'
N = N+1; TXID.N = 'CSGM'; TXDESC.N = 'GMTEXT'
N = N+1; TXID.N = 'CHAT'; TXDESC.N = 'CHAT'
N = N+1; TXID.N = 'BRDS'; TXDESC.N = 'BIRDS / BANK MAPS'
N = N+1; TXID.N = 'MNDL'; TXDESC.N = 'MANDELBROT'
N = N+1; TXID.N = 'MNDU'; TXDESC.N = 'JULIA SET'
N = N+1; TXID.N = 'BOOK'; TXDESC.N = 'BOOKING'
N = N+1; TXID.N = 'SABR'; TXDESC.N = 'SABRE DIALOG'
N = N+1; TXID.N = 'FUNC'; TXDESC.N = 'REXX FUNCTIONS'
N = N+1; TXID.N = 'WAPI'; TXDESC.N = 'WEB API DEMO'
N = N+1; TXID.N = 'BALR'; TXDESC.N = 'COLOR / UNDERLINE'
N = N+1; TXID.N = 'QAGE'; TXDESC.N = 'QUEUE AGE'
N = N+1; TXID.N = 'QAGR'; TXDESC.N = 'QUEUE AGE RESULT'
N = N+1; TXID.N = 'QUEN'; TXDESC.N = 'QUEUE ENQUEUE'
N = N+1; TXID.N = 'PROD'; TXDESC.N = 'TS PRODUCER'
N = N+1; TXID.N = 'CONS'; TXDESC.N = 'TS CONSUMER'
N = N+1; TXID.N = 'GETC'; TXDESC.N = 'GET RECORD'
N = N+1; TXID.N = 'CUST'; TXDESC.N = 'CUSTOMER MAINT'
N = N+1; TXID.N = 'SQLR'; TXDESC.N = 'SQL DEMO'
N = N+1; TXID.N = 'DODF'; TXDESC.N = 'DODFMR CALCULATOR'
N = N+1; TXID.N = 'ESDR'; TXDESC.N = 'ESDS SEQUENTIAL'
N = N+1; TXID.N = 'INQR'; TXDESC.N = 'INQUIRE DEMO'
N = N+1; TXID.N = 'FSPF'; TXDESC.N = '3270 FRAMES'
N = N+1; TXID.N = 'ESPF'; TXDESC.N = 'ESPF EDITOR'
N = N+1; TXID.N = 'CSSR'; TXDESC.N = 'PASSWORD / SIGNON'
TOTALMASTER = N

VISCOUNT = 0
DO I = 1 TO TOTALMASTER
  OK = 51
  RID = TXID.I
  EXEC CICS QUERY SECURITY RESOURCE(RID) READ(OK) END-EXEC
  IF EIBRESP = 0 & OK = 50 THEN DO
    VISCOUNT = VISCOUNT + 1
    VISID.VISCOUNT = TXID.I
    VISDESC.VISCOUNT = TXDESC.I
  END
END

PAGESIZE = 14
PAGE = 1
IF CALEN >= 1 THEN DO
  PAGE = STRIP(DFHCOMMAREA) + 0
  IF PAGE < 1 THEN PAGE = 1
END
NPAGES = 1
IF VISCOUNT > 0 THEN NPAGES = (VISCOUNT + PAGESIZE - 1) % PAGESIZE
IF PAGE > NPAGES THEN PAGE = NPAGES
FIRST = (PAGE - 1) * PAGESIZE + 1
LAST = FIRST + PAGESIZE - 1
IF LAST > VISCOUNT THEN LAST = VISCOUNT

DO SLOT = 1 TO PAGESIZE
  NUM = RIGHT(SLOT,2,'0')
  INTERPRET "OUT.L"||NUM" = ''"
END
SLOT = 0
IF VISCOUNT = 0 THEN DO
  OUT.L01 = '(NO AUTHORIZED ITEMS)'
END
ELSE DO V = FIRST TO LAST
  SLOT = SLOT + 1
  NUM = RIGHT(SLOT,2,'0')
  INTERPRET "OUT.L"||NUM" = LEFT(NUM'.  'VISID.V'  'VISDESC.V, 38)"
END
OUT.FOOTFLD = LEFT('PF3=MAIN  PF9=HELP  PF7=BWD  PF8=FWD   PAGE '||PAGE||'/'||NPAGES, 78)

EXEC CICS SEND MAP('REXMENU') MAPSET('REXMENU') FROM(OUT.) ERASE END-EXEC
EXEC CICS RECEIVE MAP('REXMENU') MAPSET('REXMENU') INTO(IN.) END-EXEC

AID = C2X(EIBAID)
IF AID = 'F1' | AID = 'F3' THEN EXEC CICS RETURN TRANSID('MYMU') END-EXEC
IF AID = 'F9' THEN DO
  CA = 'REXM'
  EXEC CICS XCTL PROGRAM('MHLP') COMMAREA(CA) END-EXEC
END
IF AID = 'F7' THEN DO
  PAGE = PAGE - 1
  IF PAGE < 1 THEN PAGE = 1
  EXEC CICS RETURN TRANSID('REXM') COMMAREA(PAGE) END-EXEC
END
IF AID = 'F8' THEN DO
  PAGE = PAGE + 1
  IF PAGE > NPAGES THEN PAGE = NPAGES
  EXEC CICS RETURN TRANSID('REXM') COMMAREA(PAGE) END-EXEC
END

SEL = STRIP(IN.SELFLD)
IF DATATYPE(SEL,'N') THEN DO
  SELNUM = SEL + 0
  IDX = FIRST + SELNUM - 1
  IF SELNUM >= 1 & SELNUM <= SLOT THEN DO
    DEST = VISID.IDX
    EXEC CICS XCTL PROGRAM(DEST) END-EXEC
  END
END
EXEC CICS RETURN TRANSID('REXM') COMMAREA(PAGE) END-EXEC
