/* SQLMENU.rexx - SQL / database submenu. Dispatcher ACL is admin. */
EXEC CICS ASSIGN USERID(UID) DATE(TODAY) TIME(NOWTIME) END-EXEC
DISPDATE = SUBSTR(TODAY,5,2)'/'SUBSTR(TODAY,7,2)'/'SUBSTR(TODAY,1,4)
DISPTIME = SUBSTR(NOWTIME,1,2)':'SUBSTR(NOWTIME,3,2)':'SUBSTR(NOWTIME,5,2)

OKSQL = 51
EXEC CICS QUERY SECURITY RESOURCE('SQLM') READ(OKSQL) END-EXEC
IF EIBRESP \= 0 | OKSQL \= 50 THEN EXEC CICS RETURN TRANSID('MYMU') END-EXEC

ROLESTR = 'ACCESS: ADMIN'
OUT.DATFLD = DISPDATE; OUT.TIMFLD = DISPTIME
OUT.USRFLD = STRIP(UID); OUT.ROLEFLD = ROLESTR

N = 0
N = N+1; TXID.N = 'SQLR'; TXDESC.N = 'SQL DEMO (REXX)'
N = N+1; TXID.N = 'SQLD'; TXDESC.N = 'SQL DEMO (COBOL)'
N = N+1; TXID.N = 'BANK'; TXDESC.N = 'BANK DEMO (SQL)'
N = N+1; TXID.N = 'BRDS'; TXDESC.N = 'BRDS (BANK MAPS)'
N = N+1; TXID.N = 'BALC'; TXDESC.N = 'BALC COLOR (BANK)'
N = N+1; TXID.N = 'BALR'; TXDESC.N = 'BALR COLOR (BANK)'
TOTALMASTER = N

VISCOUNT = 0
DO I = 1 TO TOTALMASTER
  OK = 51
  RID = TXID.I
  EXEC CICS QUERY SECURITY RESOURCE(RID) READ(OK) END-EXEC
  IF EIBRESP = 0 & OK = 50 THEN DO
    VISCOUNT = VISCOUNT + 1
    VISID.VISCOUNT = TXID.I
    VISDESC.VISCOUNT = TXDESC.I
  END
END

PAGESIZE = 8
DO SLOT = 1 TO PAGESIZE
  NUM = RIGHT(SLOT,2,'0')
  INTERPRET "OUT.L"||NUM" = ''"
END
SLOT = 0
IF VISCOUNT = 0 THEN DO
  OUT.L01 = '(NO AUTHORIZED ITEMS)'
END
ELSE DO V = 1 TO VISCOUNT
  SLOT = SLOT + 1
  NUM = RIGHT(V,2,'0')
  INTERPRET "OUT.L"||NUM" = LEFT(NUM'.  'VISID.V'  'VISDESC.V, 38)"
END
OUT.FOOTFLD = 'PF3=MAIN  PF9=HELP   ENTER=SELECT'

EXEC CICS SEND MAP('SQLMENU') MAPSET('SQLMENU') FROM(OUT.) ERASE END-EXEC
EXEC CICS RECEIVE MAP('SQLMENU') MAPSET('SQLMENU') INTO(IN.) END-EXEC

AID = C2X(EIBAID)
IF AID = 'F1' | AID = 'F3' THEN EXEC CICS RETURN TRANSID('MYMU') END-EXEC
IF AID = 'F9' THEN DO
  CA = 'SQLM'
  EXEC CICS XCTL PROGRAM('MHLP') COMMAREA(CA) END-EXEC
END

SEL = STRIP(IN.SELFLD)
IF DATATYPE(SEL,'N') THEN DO
  SELNUM = SEL + 0
  IF SELNUM >= 1 & SELNUM <= SLOT THEN DO
    DEST = VISID.SELNUM
    EXEC CICS XCTL PROGRAM(DEST) END-EXEC
  END
END
EXEC CICS RETURN TRANSID('SQLM') END-EXEC
