/* SYSMENU.rexx - System / admin submenu. Built-ins + tools. */
EXEC CICS ASSIGN USERID(UID) DATE(TODAY) TIME(NOWTIME) EIBCALEN(CALEN) END-EXEC
DISPDATE = SUBSTR(TODAY,5,2)'/'SUBSTR(TODAY,7,2)'/'SUBSTR(TODAY,1,4)
DISPTIME = SUBSTR(NOWTIME,1,2)':'SUBSTR(NOWTIME,3,2)':'SUBSTR(NOWTIME,5,2)

ROLESTR = 'ACCESS: PUBLIC'
IF STRIP(UID) \= '' THEN DO
  EXEC CICS QUERY SECURITY RESOURCE('SQLM') READ(RSQL) END-EXEC
  IF EIBRESP = 0 & RSQL = 50 THEN ROLESTR = 'ACCESS: ADMIN'
  ELSE ROLESTR = 'ACCESS: USER'
END
OUT.DATFLD = DISPDATE; OUT.TIMFLD = DISPTIME
OUT.USRFLD = STRIP(UID); OUT.ROLEFLD = ROLESTR

N = 0
/* Built-ins: show when QUERY SECURITY agrees, else signed-on fallback. */
N = N+1; TXID.N = 'CEMT'; TXDESC.N = 'MASTER TERMINAL'; TXFALL.N = 1
N = N+1; TXID.N = 'CEDA'; TXDESC.N = 'RESOURCE DEFS';    TXFALL.N = 1
N = N+1; TXID.N = 'CECI'; TXDESC.N = 'COMMAND INTERP';   TXFALL.N = 1
N = N+1; TXID.N = 'ISPF'; TXDESC.N = 'SOURCE EDITOR';    TXFALL.N = 1
N = N+1; TXID.N = 'IDCA'; TXDESC.N = 'IDCAMS';           TXFALL.N = 1
N = N+1; TXID.N = 'CSSR'; TXDESC.N = 'PASSWORD / SIGNON'; TXFALL.N = 0
N = N+1; TXID.N = 'ESPF'; TXDESC.N = 'ESPF EDITOR';      TXFALL.N = 0
N = N+1; TXID.N = 'FSPF'; TXDESC.N = '3270 FRAMES';      TXFALL.N = 0
N = N+1; TXID.N = 'INQR'; TXDESC.N = 'INQUIRE DEMO';     TXFALL.N = 0
N = N+1; TXID.N = 'GMPT'; TXDESC.N = 'GETMAIN / POINTERS'; TXFALL.N = 0
N = N+1; TXID.N = 'CSGM'; TXDESC.N = 'GMTEXT';           TXFALL.N = 0
TOTALMASTER = N

VISCOUNT = 0
DO I = 1 TO TOTALMASTER
  OK = 51
  RID = TXID.I
  EXEC CICS QUERY SECURITY RESOURCE(RID) READ(OK) END-EXEC
  ALLOWED = 0
  IF EIBRESP = 0 & OK = 50 THEN ALLOWED = 1
  /* Built-ins are not in transactions.conf; QUERY SECURITY cannot see them. */
  IF TXFALL.I = 1 & STRIP(UID) \= '' THEN ALLOWED = 1
  IF ALLOWED THEN DO
    VISCOUNT = VISCOUNT + 1
    VISID.VISCOUNT = TXID.I
    VISDESC.VISCOUNT = TXDESC.I
  END
END

PAGESIZE = 14
PAGE = 1
IF CALEN >= 1 THEN DO
  PAGE = STRIP(DFHCOMMAREA) + 0
  IF PAGE < 1 THEN PAGE = 1
END
NPAGES = 1
IF VISCOUNT > 0 THEN NPAGES = (VISCOUNT + PAGESIZE - 1) % PAGESIZE
IF PAGE > NPAGES THEN PAGE = NPAGES
FIRST = (PAGE - 1) * PAGESIZE + 1
LAST = FIRST + PAGESIZE - 1
IF LAST > VISCOUNT THEN LAST = VISCOUNT

DO SLOT = 1 TO PAGESIZE
  NUM = RIGHT(SLOT,2,'0')
  INTERPRET "OUT.L"||NUM" = ''"
END
SLOT = 0
IF VISCOUNT = 0 THEN DO
  OUT.L01 = '(NO AUTHORIZED ITEMS)'
END
ELSE DO V = FIRST TO LAST
  SLOT = SLOT + 1
  NUM = RIGHT(SLOT,2,'0')
  INTERPRET "OUT.L"||NUM" = LEFT(NUM'.  'VISID.V'  'VISDESC.V, 38)"
END
OUT.FOOTFLD = LEFT('PF3=MAIN  PF9=HELP  PF7=BWD  PF8=FWD   PAGE '||PAGE||'/'||NPAGES, 78)

EXEC CICS SEND MAP('SYSMENU') MAPSET('SYSMENU') FROM(OUT.) ERASE END-EXEC
EXEC CICS RECEIVE MAP('SYSMENU') MAPSET('SYSMENU') INTO(IN.) END-EXEC

AID = C2X(EIBAID)
IF AID = 'F1' | AID = 'F3' THEN EXEC CICS RETURN TRANSID('MYMU') END-EXEC
IF AID = 'F9' THEN DO
  CA = 'SYSM'
  EXEC CICS XCTL PROGRAM('MHLP') COMMAREA(CA) END-EXEC
END
IF AID = 'F7' THEN DO
  PAGE = PAGE - 1
  IF PAGE < 1 THEN PAGE = 1
  EXEC CICS RETURN TRANSID('SYSM') COMMAREA(PAGE) END-EXEC
END
IF AID = 'F8' THEN DO
  PAGE = PAGE + 1
  IF PAGE > NPAGES THEN PAGE = NPAGES
  EXEC CICS RETURN TRANSID('SYSM') COMMAREA(PAGE) END-EXEC
END

SEL = STRIP(IN.SELFLD)
IF DATATYPE(SEL,'N') THEN DO
  SELNUM = SEL + 0
  IDX = FIRST + SELNUM - 1
  IF SELNUM >= 1 & SELNUM <= SLOT THEN DO
    DEST = VISID.IDX
    EXEC CICS XCTL PROGRAM(DEST) END-EXEC
  END
END
EXEC CICS RETURN TRANSID('SYSM') COMMAREA(PAGE) END-EXEC
