# Add these lines to your runtime/transactions.conf
# Format: TRANSID:type:program[:groups]
MYMU:rexx:MYMENU.rexx:*
REXM:rexx:REXMENU.rexx:*
COBM:rexx:COBMENU.rexx:*
CUSM:rexx:CUSMENU.rexx:*
QUEM:rexx:QUEMENU.rexx:*
SQLM:rexx:SQLMENU.rexx:admin
SYSM:rexx:SYSMENU.rexx:*
HELP:rexx:MYHELP.rexx:*
